---
# tasks file for ppp_amiga

- name: start ppp_amiga
  debug:
    msg: Start ppp_amiga

- name: install the required software
  package:
    name: "{{ item }}"
    state: present
  loop:
    - netfilter-persistent
    - ppp

- name: copy the firewall
  template:
    src: etc/rules.v4.j2
    dest: /etc/rules.v4
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify:
    - restart firewall

- name: copy the PPP peer file
  template:
    src: "{{ ppp_peers_dir }}/amiga.j2"
    dest: "/{{ ppp_peers_dir }}/amiga"
    owner: root
    group: dip
    mode: u=rw,g=r,o=

- name: enable forwarding in the kernel
  sysctl:
    name: ipv4.forward
    reload: yes
    state: present
    sysctl_set: yes
    value: 1

  template:
    src: etc/systemd/system/pppd@.service.j2
    dest: /etc/systemd/system/pppd@.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart ppp_amiga
