---
# handlers file for ppp_amiga

- name: restart firewall
  service:
    name: netfilter-persistent
    enabled: yes
    state: restarted

- name: restart ppp_amiga
  systemd:
    name: pppd@amiga
    enabled: yes
    daemon-reload: yes
    state: restarted
