---
# handlers file for ppp_amiga

- name: restore firewall
  command: /sbin/iptables-restore < /etc/rules.v4

- name: restart ppp_amiga
  systemd:
    name: pppd@amiga
    enabled: yes
    daemon-reload: yes
    state: restarted
